config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get "archives/index"
  resources :entries
  root to: "entries#index"
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :entries
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :category
  validates :meal_type, :calories, :proteins, :carbohydrates, :fats, :category_id, presence: true
  
  def day
    self.created_at.strftime("%b %e, %Y")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  allow_browser versions: :modern
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  def index
    @entries = Entry.all.group_by(&:day)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_path, status: :see_other, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.expect(category: [ :title ])
    end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    # @entries = Entry.where("created_at >= ?", Date.today)
    @entries = Entry.all
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy!

    respond_to do |format|
      format.html { redirect_to entries_path, status: :see_other, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:meal_type, :calories, :proteins, :carbohydrates, :fats, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/archives/index.html.erb
<div class="flex gap-2 flex-col p-4">
    <% @entries.each do |day, entries| %>
        <div class="flex flex-col gap-2">
            <h3 class="text-2xl font-bold m-2">Entries for <%= day %></h1>
            <% entries.each do |entry| %>
                <%= link_to entry_path(entry) do %>
                    <div class="border flex flex-col gap-2 p-4 m-2 rounded-lg">
                        <strong><%= entry.meal_type %></strong><br/>
                        <%= entry.calories %> calories,
                        <%= entry.proteins %> proteins,
                        <%= entry.carbohydrates %> carbs,
                        <%= entry.fats %> fat,
                    </div>
            <% end %>
        <% end %>
        </div>
    <% end %>
</div>

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Title:</strong>
    <%= category.title %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit "Create category", class: "bg-blue-500 hover:bg-blue-600 p-2 rounded-lg text-white hover:cursor-pointer" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% content_for :title, "Editing category" %>

<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Categories" %>

<h1>Categories</h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %>
    <p>
      <%= link_to "Show this category", category %>
    </p>
  <% end %>
</div>

<%= link_to "New category", new_category_path %>

app/views/categories/new.html.erb
<% content_for :title, "New category" %>

<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/entries/_entry.html.erb
<div id="<%= dom_id entry %>" >
  <p>
    <strong>Meal type:</strong>
    <%= entry.meal_type %>
  </p>

  <p>
    <strong>Calories:</strong>
    <%= entry.calories %>
  </p>

  <p>
    <strong>Proteins:</strong>
    <%= entry.proteins %>
  </p>

  <p>
    <strong>Carbohydrates:</strong>
    <%= entry.carbohydrates %>
  </p>

  <p>
    <strong>Fats:</strong>
    <%= entry.fats %>
  </p>

  <% if entry.category.present? %>
    <p>
      <strong>Category:</strong>
      <%= entry.category.title %>
    </p>
  <% end %>

</div>

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div class="flex flex-col w-max">
      <h2 class="p-2 text-white font-semibold bg-red-500"><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul class="p-2 text-red-800 bg-red-100">
        <% entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :meal_type, style: "display: block" %>
    <%= form.text_field :meal_type %>
  </div>

  <div>
    <%= form.label :calories, style: "display: block" %>
    <%= form.number_field :calories %>
  </div>

  <div>
    <%= form.label :proteins, style: "display: block" %>
    <%= form.number_field :proteins %>
  </div>

  <div>
    <%= form.label :carbohydrates, style: "display: block" %>
    <%= form.number_field :carbohydrates %>
  </div>

  <div>
    <%= form.label :fats, style: "display: block" %>
    <%= form.number_field :fats %>
  </div>
  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.select :category_id, Category.all.collect {|u| [u.title, u.id]}, {}, class: "p-2 bg-gray-200 mt-2" %>
  </div>

  <div>
    <%= form.submit "Create Entry", class: "bg-blue-500 hover:bg-blue-600 p-2 rounded-lg text-white hover:cursor-pointer mt-10" %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<% content_for :title, "Editing entry" %>


<%= render "form", entry: @entry %>

<br>

<div>
  <%= link_to "Show", @entry, class: "text-blue-500 hover:underline" %> |
  <%= link_to "Back", entries_path, class: "text-blue-500 hover:underline" %>
</div>

app/views/entries/index.html.erb
<% content_for :title, "Entries" %>


<div id="entries" class="flex flex-wrap gap-2 w-max">
  <% @entries.each do |entry| %>
  <div class="border p-4 m-2 rounded-lg">
      <%= render entry %>
      <p>
        <%= link_to "Show", entry, class: "text-blue-500 hover:underline" %>
      </p>
  </div>
  <% end %>
</div>

<%= link_to "New entry", new_entry_path, class: "p-2 rounded-lg bg-green-400 text-white hover:bg-green-500 w-max my-2" %>
<%= link_to "Show all entries", archives_index_path, class: "p-2 rounded-lg bg-orange-400 text-white hover:bg-orange-500 w-max my-2" %>

app/views/entries/new.html.erb
<% content_for :title, "New entry" %>


<%= render "form", entry: @entry %>

<br>

<div>
  <%= link_to "Back", entries_path, class: "text-blue-500 hover:underline" %>
</div>

app/views/entries/show.html.erb
<%= render @entry %>

<div>
  <%= link_to "Edit", edit_entry_path(@entry), class: "text-blue-500 hover:underline" %> |
  <%= link_to "Back", entries_path, class: "text-blue-500 hover:underline" %>

  <%= button_to "Destroy", @entry, method: :delete, data: { turbo_confirm: 'Are you sure you want to delete this entry?' } , class: "p-2 rounded-lg bg-red-400 text-white hover:bg-red-500 my-2 cursor-pointer" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Foodlog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>


    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/header"%>

    <% if notice.present? %>
      <% notice_class = notice.include?("destroyed") ? "bg-red-200 text-red-500" : "bg-blue-200 text-blue-500" %>
      <div class="w-full <%= notice_class %> p-4"><%= notice %></div>
    <% end %>


    <% if alert.present?%>
      <div class="w-max bg-red-200 text-red-500 p-4"><%= alert %></div>
    <% end %>

    <div class="flex flex-col justify-center p-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<nav class="bg-teal-500 p-2 flex justify-center items-center flex-col">
    <div class="flex items-center">
        <div class="ml-10 flex items-baseline space-x-4">
            <%= link_to "Create new entry", new_entry_path, class: "p-2 rounded-lg bg-gray-200 hover:bg-gray-300" %>
        </div>
    </div>

    <div class="mt-4">
        <% if content_for(:title)%>
        <h1 class="text-lg font-semibold text-center mx-4">
            <%= yield :title%>
        </h1>
        <% else %>
            <h1 class="text-lg font-semibold text-center mx-4">Foodlog</h1>
        <% end %>
    </div>
</nav>